[project]
name = "cnexp"
version = "0.0.1"
description = "Contrastive experiments"
authors = [
    {name = "Niklas Böhm", email = "jan-niklas.boehm@uni-tuebingen.de"},
]
dependencies = [
    "torch",
    "torchvision",
    "numpy",
]
requires-python = ">=3.9"
license = {text = "EUPL"}

[project.urls]
homepage = ""


[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
